version: "3.7"

services:
  redis:
    build:
      context: ./redis
    container_name: "ad-api_dotenvrepo_redis"
    hostname: "dotenvrepo-redis"
    image: redis:alpine
  mysql:
    build:
      context: ./mysql
    image: "ad-api/dotenvrepo_mysql:latest"
    container_name: "ad-api_dotenvrepo_mysql"
    hostname: "dotenvrepo-mysql"
    #    ports:
    #      - change your override.yml
    volumes:
      - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
      - ./log/docker/mysql:/var/log/mysql:delegated
    environment:
      MYSQL_DATABASE: "rekognition"
      MYSQL_ROOT_PASSWORD: "FHb6O2ZgXoR70Okwv461ga8trE1c"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "6WjD4v5J57u9bZVbfJ59uZfEIiQK"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: dotenvrepo-mysql

  php:
    build:
      context: ./php
    image: "ad-api/dotenvrepo_php:latest"
    container_name: "ad-api_dotenvrepo_php"
    hostname: "dotenvrepo-php"
    volumes:
      - ../app:/app:consistent
      - ../docker:/docker:delegated
      - ./php/docker-entrypoint.sh:/docker/php/docker-entrypoint.sh:delegated
      - ./php/supervisor.conf:/docker/php/supervisor.conf:delegated
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.override.ini:ro
    working_dir: /app
    entrypoint: /docker/php/docker-entrypoint.sh

  nginx:
    build:
      context: ./nginx
    image: "ad-api/dotenvrepo_nginx:latest"
    container_name: "ad-api_dotenvrepo_nginx"
    hostname: "dotenvrepo-nginx"
    #    ports:
    #      - change your override.yml
    volumes:
      - ../app:/app:consistent
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/docker/nginx:/var/log/nginx:delegated
    depends_on:
      - mysql
      - php
